on: push
name: Test
jobs:
  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.4.0
        k8s-version: 1.15.1
    - name: Testing
      run: |
        minikube config set kubernetes-version=v1.15.1
        minikube start --vm-driver=none
        minikube update-context
        kubectl cluster-info
        kubectl get pods -n kube-system
